import { defineConfig, loadEnv } from "vite";
import fs from "node:fs";
import path from "path";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";

const rawPort = process.env.PORT ?? "8080";
const port = Number(rawPort);

if (Number.isNaN(port) || port <= 0) {
  throw new Error(`Invalid PORT value: "${rawPort}"`);
}

const basePath = process.env.BASE_PATH ?? "/";

function getFirebaseCompatVersion(projectRoot: string): string {
  try {
    const pkgPath = path.join(projectRoot, "node_modules", "firebase", "package.json");
    const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8")) as { version?: string };
    return pkg.version ?? "12.11.0";
  } catch {
    return "12.11.0";
  }
}

/** Vite `base` without trailing slash, for deep links from the service worker (e.g. `/app` + `/call`). */
function swAppBase(viteBase: string): string {
  if (viteBase === "/" || viteBase === "./" || viteBase === "") return "";
  return viteBase.replace(/\/$/, "");
}

/** Writes `public/firebase-messaging-sw.js` so the SW uses the same config as the app (top-level init). */
function emitFirebaseMessagingSw(projectRoot: string, mode: string, viteBase: string): void {
  const env = loadEnv(mode, projectRoot, "VITE_");
  const ver = getFirebaseCompatVersion(projectRoot);

  const init: Record<string, string> = {};
  if (env.VITE_FIREBASE_API_KEY) init.apiKey = env.VITE_FIREBASE_API_KEY;
  if (env.VITE_FIREBASE_AUTH_DOMAIN) init.authDomain = env.VITE_FIREBASE_AUTH_DOMAIN;
  if (env.VITE_FIREBASE_PROJECT_ID) init.projectId = env.VITE_FIREBASE_PROJECT_ID;
  if (env.VITE_FIREBASE_STORAGE_BUCKET) init.storageBucket = env.VITE_FIREBASE_STORAGE_BUCKET;
  if (env.VITE_FIREBASE_MESSAGING_SENDER_ID) init.messagingSenderId = env.VITE_FIREBASE_MESSAGING_SENDER_ID;
  if (env.VITE_FIREBASE_APP_ID) init.appId = env.VITE_FIREBASE_APP_ID;
  const dbUrl = env.VITE_FIREBASE_DATABASE_URL?.trim();
  if (dbUrl) init.databaseURL = dbUrl;

  const outPath = path.join(projectRoot, "public", "firebase-messaging-sw.js");
  const appBase = swAppBase(viteBase);

  const fileContent = `/* Auto-generated by Vite from VITE_* env — do not edit (regenerated on dev/build). */
importScripts("https://www.gstatic.com/firebasejs/${ver}/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/${ver}/firebase-messaging-compat.js");

if (!firebase.apps.length) {
  firebase.initializeApp(${JSON.stringify(init)});
}

const messaging = firebase.messaging();

var APP_BASE = ${JSON.stringify(appBase)};
function appPath(p) {
  p = p.charAt(0) === "/" ? p : "/" + p;
  if (!APP_BASE) return p;
  return APP_BASE + p;
}
function callUrl(queryString) {
  var q = queryString || "";
  if (q && q.charAt(0) !== "?") q = "?" + q;
  return self.location.origin + appPath("/call") + q;
}

messaging.onBackgroundMessage(function (payload) {
  console.log("[SW] Background message", payload);
  var n = payload.notification || {};
  var d = payload.data || {};
  var title = n.title || d.title || "Notification";
  var bodyText = n.body || d.body || "";
  var icon = (typeof n.icon === "string" && n.icon) ? n.icon : "/favicon.svg";

  if (d.type === "missed_call") {
    title = n.title || d.title || "Missed Call";
    bodyText = n.body || d.body || "You missed a call";
    var missedOpts = {
      body: bodyText,
      icon: "/favicon.svg",
      data: d,
      silent: false,
      vibrate: [200, 100, 200],
    };
    if (d.callerAvatar && d.callerAvatar.indexOf("http") === 0) {
      missedOpts.icon = d.callerAvatar;
      missedOpts.image = d.callerAvatar;
    }
    self.registration.showNotification(title, missedOpts);
    return;
  }

  if (d.type === "call") {
    title = n.title || d.title || "Incoming Call";
    bodyText = n.body || d.body || "Tap to answer";
    self.registration.showNotification(title, {
      body: bodyText,
      icon: "/favicon.svg",
      data: d,
      actions: [
        { action: "accept", title: "Accept" },
        { action: "reject", title: "Reject" },
      ],
    });
    return;
  }

  self.registration.showNotification(title, {
    body: bodyText || "You have a new message",
    icon: icon,
    data: d,
  });
});

self.addEventListener("notificationclick", function (event) {
  event.notification.close();
  var raw = event.notification.data || {};
  var data = {};
  Object.keys(raw).forEach(function (k) {
    data[k] = raw[k];
  });

  var url = self.location.origin + appPath("/");
  if (data.type === "missed_call") {
    if (data.callerId) {
      url =
        self.location.origin +
        appPath("/chat") +
        "?user=" +
        encodeURIComponent(data.callerId);
    } else {
      url = self.location.origin + appPath("/");
    }
  } else if (data.type === "call" && data.callId) {
    var q = new URLSearchParams();
    q.set("callId", data.callId);
    if (data.roomId) q.set("roomId", data.roomId);
    if (event.action === "accept") {
      q.set("autoAccept", "true");
    } else if (event.action === "reject") {
      q.set("reject", "true");
    }
    url = callUrl(q.toString());
  }

  event.waitUntil(
    self.clients.matchAll({ type: "window", includeUncontrolled: true }).then(function (clientsArr) {
      var i;
      var callerId = data.callerId || "";

      if (callerId && data.type === "missed_call") {
        for (i = 0; i < clientsArr.length; i++) {
          var cw = clientsArr[i];
          if (cw.url.indexOf(self.location.origin) !== 0) continue;
          if (cw.url.indexOf("/chat") === -1) continue;
          if (typeof cw.focus !== "function" || typeof cw.postMessage !== "function") continue;
          return Promise.resolve(cw.focus()).then(function () {
            cw.postMessage({ type: "OPEN_CHAT", user: callerId });
          });
        }
      }

      if (callerId && data.type === "call" && data.callId) {
        for (i = 0; i < clientsArr.length; i++) {
          var cw2 = clientsArr[i];
          if (cw2.url.indexOf(self.location.origin) !== 0) continue;
          if (cw2.url.indexOf("/chat") === -1) continue;
          if (typeof cw2.focus !== "function" || typeof cw2.postMessage !== "function") continue;
          return Promise.resolve(cw2.focus()).then(function () {
            cw2.postMessage({
              type: "OPEN_CALL",
              user: callerId,
              callId: data.callId || "",
              roomId: data.roomId || "",
              action: event.action || "",
            });
          });
        }
      }

      for (i = 0; i < clientsArr.length; i++) {
        var c = clientsArr[i];
        if (c.url.indexOf(self.location.origin) !== 0) continue;
        if (typeof c.navigate === "function") {
          return c.navigate(url).then(function (navClient) {
            return navClient ? navClient.focus() : self.clients.openWindow(url);
          });
        }
      }
      return self.clients.openWindow(url);
    })
  );
});
`;

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, fileContent, "utf8");
}

export default defineConfig(({ mode }) => {
  const projectRoot = path.resolve(import.meta.dirname);
  emitFirebaseMessagingSw(projectRoot, mode, basePath);

  return {
    base: basePath,
    plugins: [react(), tailwindcss()],
    resolve: {
      alias: {
        "@": path.resolve(import.meta.dirname, "src"),
        "@assets": path.resolve(import.meta.dirname, "..", "..", "attached_assets"),
      },
      dedupe: ["react", "react-dom"],
    },
    root: path.resolve(import.meta.dirname),
    build: {
      outDir: path.resolve(import.meta.dirname, "dist/public"),
      emptyOutDir: true,
    },
    server: {
      port,
      host: "0.0.0.0",
      allowedHosts: true,
      fs: {
        strict: true,
        deny: ["**/.*"],
      },
    },
    preview: {
      port,
      host: "0.0.0.0",
      allowedHosts: true,
    },
  };
});
