import { defineConfig, loadEnv } from "vite";
import fs from "node:fs";
import path from "path";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";

const rawPort = process.env.PORT ?? "8080";
const port = Number(rawPort);

if (Number.isNaN(port) || port <= 0) {
  throw new Error(`Invalid PORT value: "${rawPort}"`);
}

const basePath = process.env.BASE_PATH ?? "/";

function getFirebaseCompatVersion(projectRoot: string): string {
  try {
    const pkgPath = path.join(projectRoot, "node_modules", "firebase", "package.json");
    const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8")) as { version?: string };
    return pkg.version ?? "12.11.0";
  } catch {
    return "12.11.0";
  }
}

/** Vite `base` without trailing slash, for deep links from the service worker (e.g. `/app` + `/call`). */
function swAppBase(viteBase: string): string {
  if (viteBase === "/" || viteBase === "./" || viteBase === "") return "";
  return viteBase.replace(/\/$/, "");
}

/** Writes `public/firebase-messaging-sw.js` so the SW uses the same config as the app (top-level init). */
function emitFirebaseMessagingSw(projectRoot: string, mode: string, viteBase: string): void {
  const env = loadEnv(mode, projectRoot, "VITE_");
  const ver = getFirebaseCompatVersion(projectRoot);

  const init: Record<string, string> = {};
  if (env.VITE_FIREBASE_API_KEY) init.apiKey = env.VITE_FIREBASE_API_KEY;
  if (env.VITE_FIREBASE_AUTH_DOMAIN) init.authDomain = env.VITE_FIREBASE_AUTH_DOMAIN;
  if (env.VITE_FIREBASE_PROJECT_ID) init.projectId = env.VITE_FIREBASE_PROJECT_ID;
  if (env.VITE_FIREBASE_STORAGE_BUCKET) init.storageBucket = env.VITE_FIREBASE_STORAGE_BUCKET;
  if (env.VITE_FIREBASE_MESSAGING_SENDER_ID) init.messagingSenderId = env.VITE_FIREBASE_MESSAGING_SENDER_ID;
  if (env.VITE_FIREBASE_APP_ID) init.appId = env.VITE_FIREBASE_APP_ID;
  const dbUrl = env.VITE_FIREBASE_DATABASE_URL?.trim();
  if (dbUrl) init.databaseURL = dbUrl;

  const outPath = path.join(projectRoot, "public", "firebase-messaging-sw.js");
  const appBase = swAppBase(viteBase);

  const fileContent = `/* Auto-generated by Vite from VITE_* env — do not edit (regenerated on dev/build). */
importScripts("https://www.gstatic.com/firebasejs/${ver}/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/${ver}/firebase-messaging-compat.js");

if (!firebase.apps.length) {
  firebase.initializeApp(${JSON.stringify(init)});
}

const messaging = firebase.messaging();

var APP_BASE = ${JSON.stringify(appBase)};
function appPath(p) {
  p = p.charAt(0) === "/" ? p : "/" + p;
  if (!APP_BASE) return p;
  return APP_BASE + p;
}
function callUrl(queryString) {
  var q = queryString || "";
  if (q && q.charAt(0) !== "?") q = "?" + q;
  return self.location.origin + appPath("/call") + q;
}

function notifTag(payload) {
  return payload.messageId ? String(payload.messageId) : String(Date.now());
}

self.addEventListener("push", function (event) {
  try {
    if (event.data) {
      console.log("🔥 SW PUSH (raw):", event.data.json());
    } else {
      console.log("🔥 SW PUSH (raw): no data");
    }
  } catch (e) {
    console.log("🔥 SW PUSH (raw): non-json");
  }
});

messaging.onBackgroundMessage(function (payload) {
  console.log("🔥 SW PUSH:", payload);
  var pn = payload.notification || {};
  var d = payload.data || {};
  var vibrateEnabled = d.vibration === "on";
  var vibratePattern = vibrateEnabled ? [200, 100, 200, 100, 400] : undefined;
  var tag = notifTag(payload);

  if (d.type === "missed_call") {
    var titleMc = pn.title || d.title || "Missed Call";
    var bodyMc = pn.body ?? d.body ?? "You missed a call";
    var iconMc =
      pn.icon ||
      pn.image ||
      d.icon ||
      d.image ||
      "/favicon.svg";
    var missedOpts = {
      body: bodyMc,
      icon: iconMc,
      data: d,
      silent: false,
      tag: tag,
    };
    if (vibratePattern) missedOpts.vibrate = vibratePattern;
    if (d.callerAvatar && d.callerAvatar.indexOf("http") === 0) {
      missedOpts.icon = d.callerAvatar;
      missedOpts.image = d.callerAvatar;
    }
    self.registration.showNotification(titleMc, missedOpts);
    return;
  }

  if (d.type === "call") {
    var titleCall = pn.title || d.title || "Incoming Call";
    var bodyCall = pn.body ?? d.body ?? "Tap to answer";
    var iconCall =
      pn.icon ||
      pn.image ||
      d.icon ||
      d.image ||
      "/favicon.svg";
    var callOpts = {
      body: bodyCall,
      icon: iconCall,
      data: d,
      tag: tag,
      requireInteraction: true,
      actions: [
        { action: "accept", title: "Accept" },
        { action: "reject", title: "Reject" },
      ],
    };
    if (vibratePattern) callOpts.vibrate = vibratePattern;
    self.registration.showNotification(titleCall, callOpts);
    return;
  }

  var title = pn.title || d.title || "Notification";
  var body = pn.body ?? d.body ?? "";
  var icon =
    pn.icon ||
    pn.image ||
    d.icon ||
    d.image ||
    "/favicon.svg";
  var genOpts = {
    body: body,
    icon: icon,
    data: d,
    tag: tag,
  };
  if (vibratePattern) genOpts.vibrate = vibratePattern;
  self.registration.showNotification(title, genOpts);
});

self.addEventListener("notificationclick", function (event) {
  var action = event.action || "";
  var raw = event.notification.data || {};
  var data = {};
  Object.keys(raw).forEach(function (k) {
    data[k] = raw[k];
  });
  event.notification.close();

  if (data.type === "call" && data.callId) {
    if (action === "accept") {
      var qa = new URLSearchParams();
      qa.set("callId", data.callId);
      if (data.roomId) qa.set("roomId", data.roomId);
      qa.set("autoAccept", "true");
      var acceptUrl = self.location.origin + appPath("/call") + "?" + qa.toString();
      event.waitUntil(self.clients.openWindow(acceptUrl));
      return;
    }
    if (action === "reject") {
      event.waitUntil(
        self.clients.matchAll({ type: "window", includeUncontrolled: true }).then(function (clientsArr) {
          var i;
          for (i = 0; i < clientsArr.length; i++) {
            var cw = clientsArr[i];
            if (cw.url.indexOf(self.location.origin) !== 0) continue;
            if (typeof cw.focus !== "function" || typeof cw.postMessage !== "function") continue;
            return Promise.resolve(cw.focus()).then(function () {
              cw.postMessage({
                type: "OPEN_CALL",
                callId: data.callId || "",
                roomId: data.roomId || "",
                action: "reject",
              });
            });
          }
          var qr = new URLSearchParams();
          qr.set("callId", data.callId);
          if (data.roomId) qr.set("roomId", data.roomId);
          qr.set("reject", "true");
          return self.clients.openWindow(self.location.origin + appPath("/call") + "?" + qr.toString());
        })
      );
      return;
    }
  }

  var url = self.location.origin + appPath("/");
  if (data.type === "missed_call") {
    if (data.callerId) {
      url =
        self.location.origin +
        appPath("/chat") +
        "?user=" +
        encodeURIComponent(data.callerId);
    } else {
      url = self.location.origin + appPath("/");
    }
  } else if (data.type === "call" && data.callId) {
    var qd = new URLSearchParams();
    qd.set("callId", data.callId);
    if (data.roomId) qd.set("roomId", data.roomId);
    url = callUrl(qd.toString());
  }

  event.waitUntil(
    self.clients.matchAll({ type: "window", includeUncontrolled: true }).then(function (clientsArr) {
      var i;
      var callerId = data.callerId || "";

      if (callerId && data.type === "missed_call") {
        for (i = 0; i < clientsArr.length; i++) {
          var cwM = clientsArr[i];
          if (cwM.url.indexOf(self.location.origin) !== 0) continue;
          if (typeof cwM.focus !== "function" || typeof cwM.postMessage !== "function") continue;
          return Promise.resolve(cwM.focus()).then(function () {
            cwM.postMessage({ type: "OPEN_CHAT", user: callerId });
          });
        }
      }

      if (data.type === "call" && data.callId) {
        for (i = 0; i < clientsArr.length; i++) {
          var cwC = clientsArr[i];
          if (cwC.url.indexOf(self.location.origin) !== 0) continue;
          if (typeof cwC.focus !== "function" || typeof cwC.postMessage !== "function") continue;
          return Promise.resolve(cwC.focus()).then(function () {
            cwC.postMessage({
              type: "OPEN_CALL",
              user: callerId,
              callId: data.callId || "",
              roomId: data.roomId || "",
              action: action || "",
            });
          });
        }
      }

      for (i = 0; i < clientsArr.length; i++) {
        var c = clientsArr[i];
        if (c.url.indexOf(self.location.origin) !== 0) continue;
        if (typeof c.navigate === "function") {
          return c.navigate(url).then(function (navClient) {
            return navClient ? navClient.focus() : self.clients.openWindow(url);
          });
        }
      }
      return self.clients.openWindow(url);
    })
  );
});
`;

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, fileContent, "utf8");
}

export default defineConfig(({ mode }) => {
  const projectRoot = path.resolve(import.meta.dirname);
  emitFirebaseMessagingSw(projectRoot, mode, basePath);

  return {
    base: basePath,
    plugins: [react(), tailwindcss()],
    resolve: {
      alias: {
        "@": path.resolve(import.meta.dirname, "src"),
        "@assets": path.resolve(import.meta.dirname, "..", "..", "attached_assets"),
      },
      dedupe: ["react", "react-dom"],
    },
    root: path.resolve(import.meta.dirname),
    build: {
      outDir: path.resolve(import.meta.dirname, "dist/public"),
      emptyOutDir: true,
    },
    server: {
      port,
      host: "0.0.0.0",
      allowedHosts: true,
      fs: {
        strict: true,
        deny: ["**/.*"],
      },
    },
    preview: {
      port,
      host: "0.0.0.0",
      allowedHosts: true,
    },
  };
});
